export type FilmType = {
  start_time: string,
  original_title: string,
  french_title: string,
  runtime: number,
  synopsis: string,
  cast: string,
  languages: string,
  genres: string,
  release_date: string,
  rating: number,
  imdb_url: string,
  origin_country: string,
  poster_hi_res: string,
  poster_lo_res: string,
  tagline: string,
  cinema_address: string,
  cinema_name: string,
  cinema_town: string
}
